### ISSUE TITLE
[BUILD]  AttributeError: module 'sipbuild.api' has no attribute 'prepare_metadata_for_build_wheel'

### ISSUE THREAD

**Issue by jinfagang** [PyQt5/PyQt#149]
```
 hook = backend.prepare_metadata_for_build_wheel
      AttributeError: module 'sipbuild.api' has no attribute 'prepare_metadata_for_build_wheel'

      During handling of the above exception, another exception occurred:
```

**Comment by 892768447** [comment]
这是做什么操作遇到的？

**Comment by Reda-BENMAKDAD** [comment]
this issue occurs when installing "pyqt5-tools" with the command "pip install pyqt5-tools" on windows.

**Comment by 892768447** [comment]
because this repo [pyqt5-tools](https://github.com/altendky/pyqt-tools) is build from source.
you can issues on here https://github.com/altendky/pyqt-tools

**Comment by iT-Boyer** [comment]
pip 版本：
```
$ pip --version

pip 22.0.4 from /Users/boyer/.pyenv/versions/3.10.1/lib/python3.10/site-packages/pip (python 3.10)
```

错误信息：
` AttributeError: module 'sipbuild.api' has no attribute 'prepare_metadata_for_build_wheel'`
```
# me @ M1 in ~/hsg/emacs-application-frameworkgit:(master) [19:51:23] 
$ ./install-eaf.py
[EAF] ------------------------------------------
[EAF] Installing core dependencies
[EAF] Running pip install --user epc pyqt5 pyqt5-sip pyqtwebengine mac-app-frontmost @ /Users/me/emacs-application-framework
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting epc
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/55/ae/f7b329fa2bc9932a416e8846e78e06ce3e13a20e5c3f2cf80a18f489dec1/epc-0.0.5.tar.gz (17 kB)
  Preparing metadata (setup.py) ... done
Collecting pyqt5
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/3b/27/fd81188a35f37be9b3b4c2db1654d9439d1418823916fe702ac3658c9c41/PyQt5-5.15.6.tar.gz (3.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [29 lines of output]
      Traceback (most recent call last):
        File "/Users/boyer/.pyenv/versions/3.10.1/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 156, in prepare_metadata_for_build_wheel
          hook = backend.prepare_metadata_for_build_wheel
      AttributeError: module 'sipbuild.api' has no attribute 'prepare_metadata_for_build_wheel'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/Users/boyer/.pyenv/versions/3.10.1/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/Users/boyer/.pyenv/versions/3.10.1/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/boyer/.pyenv/versions/3.10.1/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 160, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "/private/var/folders/yf/qzly_ww53nv0wn2w7hf9rs880000gn/T/pip-build-env-3oddpiu4/overlay/lib/python3.10/site-packages/sipbuild/api.py", line 51, in build_wheel
          project = AbstractProject.bootstrap('pep517')
        File "/private/var/folders/yf/qzly_ww53nv0wn2w7hf9rs880000gn/T/pip-build-env-3oddpiu4/overlay/lib/python3.10/site-packages/sipbuild/abstract_project.py", line 83, in bootstrap
          project.setup(pyproject, tool, tool_description)
        File "/private/var/folders/yf/qzly_ww53nv0wn2w7hf9rs880000gn/T/pip-build-env-3oddpiu4/overlay/lib/python3.10/site-packages/sipbuild/project.py", line 594, in setup
          self.apply_user_defaults(tool)
        File "/private/var/folders/yf/qzly_ww53nv0wn2w7hf9rs880000gn/T/pip-install-iwxqhwkt/pyqt5_f6291fbfee524f7e8515567167a9c714/project.py", line 63, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "/private/var/folders/yf/qzly_ww53nv0wn2w7hf9rs880000gn/T/pip-build-env-3oddpiu4/overlay/lib/python3.10/site-packages/pyqtbuild/project.py", line 70, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "/private/var/folders/yf/qzly_ww53nv0wn2w7hf9rs880000gn/T/pip-build-env-3oddpiu4/overlay/lib/python3.10/site-packages/sipbuild/project.py", line 241, in apply_user_defaults
          self.builder.apply_user_defaults(tool)
        File "/private/var/folders/yf/qzly_ww53nv0wn2w7hf9rs880000gn/T/pip-build-env-3oddpiu4/overlay/lib/python3.10/site-packages/pyqtbuild/builder.py", line 67, in apply_user_defaults
          raise PyProjectOptionException('qmake',
      sipbuild.pyproject.PyProjectOptionException
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
